### ISSUE TITLE
Creative Assignment 2 is ready for submission!

### ISSUE THREAD

**Issue by saraarman** [VIS-2129-F2020/sara_arman-vis#2]
Dear Carole and Alex, 

Creative Assignment 2 is ready for submission. Here is the link to the HTML: [https://vis-2129-f2020.github.io/sara_arman-vis/Creative-Assignment-2-Final.html]

Let me know if you have any questions! 

Thanks, 
Sara

**Comment by bauranov** [comment]
Great job, you explored different maps and tried to plot various data. I am not sure why the proportional map displays the same sizes. You can send me an email if you would like to explore more.

At the beginning of a code chunk add {r, message=FALSE,warning=FALSE} to suppress messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (such as in the section Continous cartogram). If there is such text, remove it with the code I mentioned above.

Keep up the good work, looking forward to your next assignment!
