### ISSUE TITLE
Creative Assignment 3 is completed!

### ISSUE THREAD

**Issue by saraarman** [VIS-2129-F2020/sara_arman-vis#3]
Dear Carole and Alex, 

I have completed Assignment 3. Thank you so much for the extension. Here is the link: 
[https://vis-2129-f2020.github.io/sara_arman-vis/Assignment-3](url)

I hope you enjoy reviewing it! 

Best, 
Sara

**Comment by bauranov** [comment]
Other than the huge message in Section 6 (Question 6), awesome work!
