### ISSUE TITLE
Creative Assignment 4 is complete!

### ISSUE THREAD

**Issue by saraarman** [VIS-2129-F2020/sara_arman-vis#4]
Dear Carole and Alex, 

Creative Assignment 4 is ready for review. You can find it at this link: [https://vis-2129-f2020.github.io/sara_arman-vis/Creative-Assignment-4-FINAL](url)

Thank you so much! 

Best, 
Sara

**Comment by bauranov** [comment]
Very interesting to see there's so much variation in the walking areas. I hope this is useful for your studio. Good work!
